In [ ]:
import numpy as np
A = np.array([[3, 4, 5],[6 ,7, 8]])
B = np.array([[1, 2, 3],[4, 5, 6]])
  
print(A)
print(B)

b= B.transpose()
print(b)



[[3 4 5]
 [6 7 8]]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
mul= np.dot(A,b)
print(mul)

[[ 26  62]
 [ 44 107]]


In [ ]:
C = np.array([[1, 0],[0, 2]])
c= np.linalg.inv(C)
print(c)

add = mul.__add__(c)
print(add)

[[1.  0. ]
 [0.  0.5]]
[[ 27.   62. ]
 [ 44.  107.5]]
